# Site
name: 'Hümayun Yayınları'
language: "tr"
description: 'Tarihimiz Yeniden Milletin Oluncaya Kadar...'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon/favicon.ico'
baseurl: ''

# Social Settings
disqus: #'demowebsite'
email: 'iletisim@humayunyayinlari.com'
mailchimp-list: #'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
google_analytics: #''
katalogurl: 'https://cdn.e-damla.com.tr/PUBLIC/Kataloglar/humayun-yayinlari/index.html'
twitter: 'https://twitter.com/humayunyayin'
facebook: 'https://www.facebook.com/humayunyayin'
instagram: 'https://instagram.com/humayunyayin'
youtube: 'https://www.youtube.com/channel/UCL3XyWMFNCam7Z8wIr6Ce5A'

pagepreview:
  enabled: true
  prefix: 'https://cdn.e-damla.com.tr/damlayayinevi_ornek_sayfalar/'
  postfix: '/index.html'

include: ["_pages"]
permalink: /:title/


# BuyOut Ecommerce
buyout:
  enabled: true
  #buyout websites:
  damlayayinevi: true
  hepsiburada: true
  dnr: true
  idefix: true
  kitapyurdu: true
  odatvkitap: false
  bkmkitap: true
  amazontr: true
  dkitap: true

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
  - jekyll-gist
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      avatar: /assets/images/avatar.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

  # all books
  - scope:
      path: "_books"
    values:
      layout: book

  # all authors
  - scope:
      path: "_authors"
    values:
      layout: author

  # all persons
  - scope:
      path: "_persons"
    values:
      layout: person

  # all illustrators
  - scope:
      path: "_illustrators"
    values:
      layout: illustrator

  # all translators
  - scope:
      path: "_translators"
    values:
      layout: translator
      
# Syntax
markdown: kramdown
highlighter: rouge

# XML feed
feed:
  collections:
    books:
      path: "/kitaplar/feed.xml"
    authors:
      path: "/yazarlar/feed.xml"

# excerpt
excerpt_separator: <!--more-->

# Paginate
paginate: 10
paginate_path: /page:num/
paginate_path: "/blog/page:num/"

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

collections:
  books:
    output: true
    permalink: /kitaplar/:title
    sort_by: publish-number
  authors:
    output: true
    permalink: /yazarlar/:title
  illustrators:
    output: true
    permalink: /tasarimcilar/:title
  translators:
    output: true
    permalink: /cevirmenler/:title
  persons:
    output: true
    permalink: /sahsiyetler/:title

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
